---
title: Hoe de Pen uitbreidingen toe te voegen
hero_image: images/banner.png
description: generic-scratch3-toevoegen-pen-uitbreiding beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2018/11/26"
steps:
  - 
    title: Inleiding
