---
title: Hoe de Pen uitbreiding toe te voegen
hero_image: images/banner.png
description: beschrijving algemeen-scratch3-pen-toevoegen-uitbreiding
version: 4
listed: false
copyedit: false
last_tested: "2018/11/26"
steps:
  - title: Inleiding
