title: generic-scratch3-add-pen-extension
hero_image: images/banner.png
description: generic-scratch3-add-pen-extension description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Introduction
