---
title: पेन विस्तार कसा जोडावा
hero_image: images/banner.png
description: generic-scratch3-add-pen-extension वर्णन
version: 0
listed: false
copyedit: false
last_tested: "२०१८-११-२६"
steps:
  - 
    title: परिचय
