---
title: Как добавить расширение Перо
hero_image: images/banner.png
description: описание generic-scratch3-add-pen-extension
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Введение
