---
title: பேனா நீட்டிப்பை எவ்வாறு சேர்ப்பது
hero_image: படங்கள்/banner.png
description: பொதுவான-ஸ்க்ராட்ச் 3-சேர்-பேனா-நீட்டிப்பு விளக்கம்
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: அறிமுகம்
