---
title: Hvordan legge til Penn-utvidelsen
hero_image: images/banner.png
description: generisk-scratch3-legg-til-penn-utvidelse beskrivelse
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introduksjon
