---
title: Cómo añadir la extensión Lápiz
hero_image: images/banner.png
description: descripción de generic-scratch3-add-pen-extension
version: 4
listed: false
copyedit: false
last_tested: "2018-26-01"
steps:
  - 
    title: Introducción
