---
title: Sut i ychwanegu'r estyniad Pin
hero_image: images/banner.png
description: disgrifiad generig-scratch3-add-pen-estyniad
version: 3
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Cyflwyniad
