---
title: So fügen Sie die Stifterweiterung hinzu
hero_image: images / banner.png
description: Beschreibung des Hinzufügens der allgemeinen-Scratch3-Malstift-Erweiterung
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Einführung
