---
title: Cara menambahkan ekstensi Pena
hero_image: images/banner.png
description: deskripsi generik-scratch3-tambah-pena-ekstensi
version: 4
listed: false
copyedit: false
last_tested: "2018-26-01"
steps:
  - 
    title: Pengenalan
