---
title: Com afegir l’extensió del Llapis
hero_image: images/banner.png
description: descripció afegir-extensió-genérica-al-llapis-en-scratch3
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introducció
