---
title: Jak dodać rozszerzenie Pióro
hero_image: images/banner.png
description: generic-scratch3-add-pen-extension opis
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Wprowadzenie
