---
title: Comment ajouter l'extension Stylo
hero_image: images/banner.png
description: description générique de scratch3-ajouter-extension stylo
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Introduction
