---
title: පෙන් දිගුව(Pen Extension) එකතු කරන්නේ කෙසේද
hero_image: images/banner.png
description: generic-screwch3-add-pen-extension විස්තරය
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: හැදින්වීම
